### ISSUE TITLE
Decide on a License

### ISSUE THREAD

**Issue by AdrianKoshka** [nixheads/yt-scripts#1]
I haven't quite decided how to license this repo...I feel like it could fall under an number of them

- CC-0
- CC BY SA
- CC BY NC SA
- GNU FDL (Free Documentation License)
- Public Domain

perhaps @shymega could help me choose.

**Comment by shymega** [comment]
Theodore Seán Tubbs <notifications@github.com> writes:

> I haven't quite decided how to license this repo...I feel like it
> could fall under an number of them

> - CC-0

Not a bad license, works quite well, and *appears* to be recommended
by the GNU project (as a "free" license), if that's your thing.

> - CC BY SA

This is a good license. It enforces attribution of the original work
(Well, enforces is an objective term - the license can't do that by
itself, but it can help *encourage* enforcement) and makes the works
ShareAlike, which means the same license must be used.

I know this "viral" nature is not too popular with *some* people, but
it has helped the free culture/software movement immensely over the
years, and (IMHO) should be upheld.

> - CC BY NC SA

This is noted by RMS to be a non-free license, as it restricts
commercial usage, which in turn violates Freedom 0 - "The freedom to
run the program as you wish, for any purpose".

I'm not sure if you *want* to restrict commercial usage, but it's your
call, really.

> - GNU FDL (Free Documentation License)

I don't know much about this license to be honest. I would,
personally, say that the CC-0 license is a better one than this, as
that's more designed for "free cultural" works, rather than
documentation - AFAICT, the FDL is for documentation.. but I'm not too
sure, as I say..

> - Public Domain

This is not a "license", per se, it just waivers your copyright over
works - is that what you want? 

> perhaps @shymega could help me choose.

Indeed I can!

I would be inclined to suggest you go with the CC-SA license, as

- It's recommended by the FSF.
- It's straight to the point and provides the essential freedoms and
- allows derivative works and attribution to the original works (This repo!)
- It's clear to the point.

*However*, this is *all* up to you.

I'm just an adviser here.

-- 
Best regards,
Dom Rodriguez

**Comment by AdrianKoshka** [comment]
I decided on ``CY-BY-SA``

- afe3c06c8b40502ebdb8b6bfaa085fe400df47cb
- 39661756dadbbb34f1ecc027f47f63a5c66f35b0
